services:
  # Backend Service
  - type: web
    name: family-event-planner-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      # Gmail MCP Configuration
      - key: PARENT1_EMAIL
        value: joyce.yan.zhang@gmail.com
      - key: PARENT2_EMAIL
        value: sheridan.gray@gmail.com
      - key: MCP_GMAIL_CREDENTIALS
        sync: false
      - key: GOOGLE_OAUTH_TOKEN
        sync: false
      
      # Twilio MCP Configuration  
      - key: TWILIO_PHONE_TO
        value: +12063909727
      - key: MCP_TWILIO_CREDENTIALS
        sync: false

      # GitHub MCP Configuration
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false

      # Render MCP Configuration
      - key: RENDER_API_KEY
        sync: false

      # These settings have been migrated to the database:
      # - Location Settings (home_address, max_distance_miles)
      # - Schedule Settings (weekday_earliest_time, weekend_earliest_time, weekend_nap_start, weekend_nap_end)
      # - Event Preferences (min_child_age, max_child_age, max_cost_per_event, min_advance_days, max_advance_months)
      # - Registration Info (parent names, child info, emergency contact)
      # - Event Discovery Settings (events_per_week_min/max, events_per_day_max, scan_frequency_hours, urgent_scan_frequency_hours)
      # All family configuration is now managed via the admin interface.

      # Application Settings
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: API_KEY
        value: fep_secure_api_key_2024_$7mK9pL2nQ8xV3wR6zA


      # Google OAuth (temporary - used only for initial setup)
      - key: GOOGLE_CLIENT_ID
        value: 584799141962-3mfn2p032ihqfkjhbu8v8jl8pcmp45ie.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://sheridangray.com
      - key: WEBHOOK_BASE_URL
        value: https://family-event-planner-backend.onrender.com
      - key: GOOGLE_CLOUD_PROJECT_ID
        value: family-event-planner-469218
      - key: PUBSUB_TOPIC_NAME
        value: gmail-notifications

      # Together.ai API for LLM Age Evaluation
      - key: TOGETHER_AI_API_KEY
        sync: false

      # OpenWeatherMap API for Weather Filtering
      - key: WEATHER_API_KEY
        sync: false
      - key: GMAIL_WEBHOOK_JWT_SECRET
        sync: false

      # Database Configuration (will be auto-populated by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: family-event-planner-db
          property: connectionString

  # Frontend Service  
  - type: web
    name: family-event-planner-frontend
    env: node
    plan: starter
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    startCommand: npm start -- --port $PORT
    envVars:
      # Frontend API Configuration
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://family-event-planner-backend.onrender.com/api
      - key: NEXT_PUBLIC_API_KEY
        value: fep_secure_api_key_2024_$7mK9pL2nQ8xV3wR6zA

      # NextAuth Configuration  
      - key: NEXTAUTH_URL
        value: https://family-event-planner-frontend.onrender.com
      # When ready to switch to custom domain, change NEXTAUTH_URL to:
      # value: https://sheridangray.com
      - key: NEXTAUTH_SECRET
        value: 2LZ2uGJMDSEYZtg1tThFl+ayEyQv9CBtnGZc0YniS64=
      - key: AUTH_TRUST_HOST
        value: "true"

      # Google OAuth for NextAuth
      - key: GOOGLE_CLIENT_ID
        value: 584799141962-3mfn2p032ihqfkjhbu8v8jl8pcmp45ie.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      # Allowed email addresses for family access
      - key: ALLOWED_EMAILS
        value: "joyce.yan.zhang@gmail.com,sheridan.gray@gmail.com"

      - key: NODE_ENV
        value: production

# Database
databases:
  - name: family-event-planner-db
    databaseName: family_event_planner
    user: family_event_planner